name: Lint GitHub Actions workflows
on: pull_request
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
      - name: Lint actionlint with reviewdog
        if: ${{ failure() }}
        uses: reviewdog/action-actionlint@v1
