name: Lint GitHub Actions workflows
on: pull_request
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
      - name: Lint actionlint with reviewdog
        if: ${{ failure() }}
        uses: reviewdog/action-actionlint@v1
