name: Lint GitHub Actions workflows
on: pull_request
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
      - name: Lint actionlint with reviewdog
        if: ${{ failure() }}
        uses: reviewdog/action-actionlint@v1
