name: Test opa policy
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 1'
jobs:
  conftest:
    name: Test opa policy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: checkout
    - name: test open policy agent for circleci
      run: docker run -v `pwd`:`pwd` -w `pwd` --rm openpolicyagent/opa test -v .circleci/policy/
