name: Test opa policy
on:
  push:
  pull_request:
jobs:
  conftest:
    name: Test opa policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        name: checkout
      - name: test open policy agent for circleci
        uses: docker://openpolicyagent/opa:latest
        with:
          args: test -v .circleci/policy/
