name: Test opa policy
on:
  push:
  pull_request:
jobs:
  conftest:
    name: Test opa policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
        name: checkout
      - name: test open policy agent for circleci
        uses: docker://openpolicyagent/opa:latest
        with:
          args: test -v .circleci/policy/
