name: Test opa policy
on:
  push:
  pull_request:
jobs:
  conftest:
    name: Test opa policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        name: checkout
      - name: test open policy agent for circleci
        uses: docker://openpolicyagent/opa:latest
        with:
          args: test -v .circleci/policy/
