name: Test opa policy
on:
  push:
  pull_request:
jobs:
  conftest:
    name: Test opa policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: checkout
      - name: test open policy agent for circleci
        uses: docker://openpolicyagent/opa:latest
        with:
          args: test -v .circleci/policy/
