name: Secretlint
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 1'
env:
  CI: true
jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: lint with secretlint on docker
        run: |
           docker run -v "$(pwd)":"$(pwd)" \
             -w "$(pwd)" \
             --rm \
             secretlint/secretlint:latest secretlint \
             --format @secretlint/secretlint-formatter-sarif \
             --output results.sarif \
             "**/*"
      - name: upload sarif file
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results.sarif'
          category: 'secretlint'
