name: yamllint
on: pull_request
jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
        name: checkout
      - name: run yamllint
        run: |
          yamllint --version
          yamllint -c .github/workflows/.yamllint .github/
      - name: run yamllint
        if: ${{ failure() }}
        uses: reviewdog/action-yamllint@v1.8.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: '-c .github/workflows/.yamllint .github/'
